// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOFfkyOfBzWvGFzZ7uoOoZPBNC9TmlR7o',
    appId: '1:343506080479:web:9a3c233524ddb509e70f6a',
    messagingSenderId: '343506080479',
    projectId: 'remindgemini',
    authDomain: 'remindgemini.firebaseapp.com',
    storageBucket: 'remindgemini.appspot.com',
    measurementId: 'G-CVY321SQZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCearWLuaXenAkI_EEDZnM-Wh-H_OxWkE',
    appId: '1:343506080479:android:6f2a0524c6ac42d5e70f6a',
    messagingSenderId: '343506080479',
    projectId: 'remindgemini',
    storageBucket: 'remindgemini.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJrVOIbrwH2c45ufbFaI8p-WEHYWF-uV0',
    appId: '1:343506080479:ios:2d11a0ce854e8f96e70f6a',
    messagingSenderId: '343506080479',
    projectId: 'remindgemini',
    storageBucket: 'remindgemini.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJrVOIbrwH2c45ufbFaI8p-WEHYWF-uV0',
    appId: '1:343506080479:ios:2d11a0ce854e8f96e70f6a',
    messagingSenderId: '343506080479',
    projectId: 'remindgemini',
    storageBucket: 'remindgemini.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOFfkyOfBzWvGFzZ7uoOoZPBNC9TmlR7o',
    appId: '1:343506080479:web:4b53ccec692cdd8fe70f6a',
    messagingSenderId: '343506080479',
    projectId: 'remindgemini',
    authDomain: 'remindgemini.firebaseapp.com',
    storageBucket: 'remindgemini.appspot.com',
    measurementId: 'G-YHFHD1SGXQ',
  );
}
